services:
  reverse:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites-enabled:/etc/caddy/sites-enabled
      - ./authentik:/etc/caddy/authentik
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: